OpenTfsPortal/Models/DashboardDesenvolvedorViewModel.cs
using Otfs.ProjectManagement.Core.Domain.Model;
using Otfs.ProjectManagement.Core.Domain.Model.Task;
using System;
using System.Collections.Generic;
using System.Linq;

namespace OpenTfsPortal.Models
{
    public class DashboardDesenvolvedorViewModel
    {
        public Guid UserId { get; set; }
        public string Desenvolvedor { get; set; }
        public IEnumerable<OtfsTask> Tarefas { get; set; }

        public Dictionary<string, List<OtfsTask>> AgruparTarefasPorProjeto()
        {
            var tasks = from t in Tarefas
                        group t by t.NomeProjeto into g
                        select new { projetos = g.Key, tarefas = g.ToList() };

            return tasks.ToDictionary(x => x.projetos, x => x.tarefas);
        }
    }
}

OpenTfsPortal/Controllers/DashboardController.cs
using OpenTfsPortal.Models;
using Otfs.ProjectManagement.Core.Application;
using Otfs.ProjectManagement.Core.Domain.Model;
using Otfs.ProjectManagement.Core.Domain.Model.BacklogItem;
using Otfs.ProjectManagement.Core.Domain.Model.Project;
using System;
using System.Web.Mvc;

namespace OpenTfsPortal.Controllers
{
    [Authorize]
    [RoutePrefix("Dashboard")]
    public class DashboardController : ApplicationController
    {
        private IOtfsBacklogItemServices _otfsBacklogItemServices;
        private IOtfsProjectServices _otfsProjectServices;
        private IOtfsTaskServices _otfsTaskServices;

        public DashboardController(
            IOtfsBacklogItemServices otfsBacklogItemServices,
            IOtfsProjectServices otfsProjectServices,
            IOtfsTaskServices otfsTaskServices)
        {
            _otfsTaskServices = otfsTaskServices;
            _otfsProjectServices = otfsProjectServices;
            _otfsBacklogItemServices = otfsBacklogItemServices;
        }


        [Route("Desenvolvedor")]
        public ActionResult DashboardDesenvolvedor()
        {
            var dashboardDesenvolvedor = new DashboardDesenvolvedorViewModel
            {
                UserId = UsuarioAutorizadoSession.Id,
                Tarefas = _otfsTaskServices.RetornarTarefas(),
                Desenvolvedor = UsuarioAutorizadoSession.Nome
            };

            return View(dashboardDesenvolvedor);
        }


        [Route("Timer")]
        public ActionResult DashboardTimer()
        {
            var id = new OtfsProjectId(202);

            var backlogsItemsPendentes = _otfsBacklogItemServices.RetorarBacklogItens(id, "documentosfiscais.set.govrn\\Implementações de Abril");

            var model = new DashboardAuditorViewModel
            {
                Interation = "documentosfiscais.set.govrn\\Implementações de Abril",
                FimSprint = null,
                InicioSprint = null,
                ItemsPendentes = backlogsItemsPendentes.BacklogsItemsPendentes,
                ItemsAndamento = backlogsItemsPendentes.BacklogsItemsAndamento,
                ItemsComitadas = backlogsItemsPendentes.BacklogsItemsParaTestes,
                ItemsParaBuild = backlogsItemsPendentes.BacklogsItemsParaBuild,
                ItemsPublicados = backlogsItemsPendentes.BacklogsItemsPublicados
            };

            return View(model);
        }


        [Route("Auditor")]
        public ActionResult DashboardAuditorFiscal(int projectId, string path, DateTime? inicio, DateTime? fim)
        {
            var id = new OtfsProjectId(projectId);

            var backlogsItemsPendentes = _otfsBacklogItemServices.RetorarBacklogItens(id, path);

            var model = new DashboardAuditorViewModel
            {
                Interation = path,
                FimSprint = fim,
                InicioSprint = inicio,
                ItemsPendentes = backlogsItemsPendentes.BacklogsItemsPendentes,
                ItemsAndamento = backlogsItemsPendentes.BacklogsItemsAndamento,
                ItemsComitadas = backlogsItemsPendentes.BacklogsItemsParaTestes,
                ItemsParaBuild = backlogsItemsPendentes.BacklogsItemsParaBuild,
                ItemsPublicados = backlogsItemsPendentes.BacklogsItemsPublicados
            };

            return View(model);
        }

        [Route("Infra")]
        public ActionResult DashboardInfraestrutura()
        {
            var projetos = _otfsProjectServices.RetornarTodosProjetos();
            var estorias = _otfsBacklogItemServices.RetornarBacklogsItemsParaBuild();

            return View(new DashboardInfraViewModel(projetos, estorias));
        }

        [HttpPost]
        public ActionResult Approve(int backlogItemId, string iteration)
        {
            var backlogItem = _otfsBacklogItemServices.AprovarBackLogItemParaCompilacao(new OtfsBacklogItemId(backlogItemId), iteration);

            var routeObject = new
            {
                projectId = backlogItem.ProjectId.Id,
                path = backlogItem.Iteration.Path,
                inicio = backlogItem.Iteration.StartDate,
                fim = backlogItem.Iteration.EndDate
            };

            return RedirectToAction("DashboardAuditorFiscal", routeObject);
        }

        [HttpPost]
        public ActionResult Concluir(int backlogItemId, string iteration)
        {
            var backlogItem = _otfsBacklogItemServices.ConcluirBackLogItemParaCompilacao(new OtfsBacklogItemId(backlogItemId), iteration);

            var routeObject = new
            {
                projectId = backlogItem.ProjectId.Id,
                path = backlogItem.Iteration.Path,
                inicio = backlogItem.Iteration.StartDate,
                fim = backlogItem.Iteration.EndDate
            };

            return RedirectToAction("DashboardAuditorFiscal", routeObject);
        }

        [HttpPost]
        public ActionResult Deny(int backlogItemId, string motivo, string iteration)
        {
            var mensagem = string.Format("Tarefa reprovada por {0} motivo: {1}", User.Identity.Name, motivo);
            var backlogItem = _otfsBacklogItemServices.RejeitarBackLogItem(new OtfsBacklogItemId(backlogItemId), iteration, mensagem);

            var routeObject = new
            {
                projectId = backlogItem.ProjectId.Id,
                path = backlogItem.Iteration.Path,
                inicio = backlogItem.Iteration.StartDate,
                fim = backlogItem.Iteration.EndDate
            };

            return RedirectToAction("DashboardAuditorFiscal", routeObject);
        }
        
        public ActionResult MarcarProjetoPublicado(int id)
        {
            _otfsBacklogItemServices.MarcarBackLogItemPublicado(new OtfsProjectId(id));

            return RedirectToAction("DashboardInfraestrutura");
        }

        public ActionResult Preview()
        {
            return View();
        }
    }
}

OpenTfsPortal/Controllers/ProdutividadeController.cs
using OpenTfsPortal.Models;
using Otfs.GestaoHoras.Core.Aplication;
using Otfs.GestaoHoras.Core.Domain.Model;
using Otfs.GestaoHoras.Data;
using Otfs.GestaoHoras.Data.Externa;
using System;
using System.Web.Mvc;


namespace OpenTfsPortal.Controllers
{
    [Authorize]
    public class ProdutividadeController : ApplicationController
    {
        private IOtfsProdutividadeService<OtfsProdutividadeRepository> _tfsRepository;
        private IOtfsProdutividadeService<OtfsHorasPontoRepository> _pontoRepository;
        private IOtfsProdutividadeService<OtfsHorasItopRepository> _itopRepository;
        private IOtfsLancamentoHoraService _otfsLancamentoHoraService;


        public ProdutividadeController(
            IOtfsProdutividadeService<OtfsProdutividadeRepository> tfsRepository,
            IOtfsProdutividadeService<OtfsHorasPontoRepository> pontoRepository,
            IOtfsProdutividadeService<OtfsHorasItopRepository> itopRepository,
            IOtfsLancamentoHoraService otfsLancamentoHoraService)
        {
            _tfsRepository = tfsRepository;
            _itopRepository = itopRepository;
            _pontoRepository = pontoRepository;
            _otfsLancamentoHoraService = otfsLancamentoHoraService;
        }

        public ActionResult ListarHoras(int taskId, string title)
        {
            var listarHoras = new ListaHorasViewModel
            {
                TaskId = taskId,
                Title = title,
                HorasLancadas = _otfsLancamentoHoraService.ListarHoras(taskId)
            };

            return View(listarHoras);
        }

        public ActionResult LancarHora(int taskId, string title)
        {
            var model = new LancamentoHoraViewModel
            {
                TaskId = taskId,
                UserId = this.UsuarioAutorizadoSession.Id,
                Data = DateTime.Today,
                DataLancamento = DateTime.Today,
                Title = title
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult LancarHora(LancamentoHora model)
        {
            _otfsLancamentoHoraService.InserirLancamentoHora(model);

            return Redirect("~/Dashboard/Desenvolvedor");
        }

        public ActionResult ExcluirHora(int id)
        {
            return View(_otfsLancamentoHoraService.BuscarHoraPorId(id));
        }

        [HttpPost]
        public ActionResult ExcluirHora(int id, int taskId, string title)
        {
            _otfsLancamentoHoraService.ExcluirHora(id);

            var listarHoras = new ListaHorasViewModel
            { 
                TaskId = taskId, 
                Title = title,
                HorasLancadas = _otfsLancamentoHoraService.ListarHoras(taskId)
            };

            return View("ListarHoras", listarHoras);
        }

        public ActionResult EditarHora(int id, string title)
        {
            var lancamentoHora = _otfsLancamentoHoraService.BuscarHoraPorId(id);

            var model = new LancamentoHoraViewModel
            {
                Id = lancamentoHora.Id,
                TaskId = lancamentoHora.TaskId,
                UserId = lancamentoHora.UserId,
                Data = lancamentoHora.Data,
                HoraTrabalhada = lancamentoHora.HoraTrabalhada,
                DataLancamento = lancamentoHora.DataLancamento,
                Historico = lancamentoHora.Historico,
                Title = title
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult EditarHora(LancamentoHora model)
        {
            _otfsLancamentoHoraService.AtualizarHora(model);

            var listarHoras = new ListaHorasViewModel 
            { 
                TaskId = model.TaskId, 
                HorasLancadas = _otfsLancamentoHoraService.ListarHoras(model.TaskId)
            };

            return View("ListarHoras", listarHoras);
        }

        public ActionResult DashboardHoras()
        {
            var data = DateTime.Parse("01/03/2015");
            var userId = this.UsuarioAutorizadoSession.Id;

            var horasTfs = _tfsRepository.ListarHorasMes(userId, data.Month);
            var horasponto = _pontoRepository.ListarHorasMes(userId, data.Month);
            var horasItop = _itopRepository.ListarHorasMes(userId, data.Month);

            return View(new DashboardHoraViewModel(data, horasTfs, horasponto, horasItop));
        }
    }
}

OpenTfsPortal/Controllers/ProjectManagementController.cs
using OpenTfsPortal.Models;
using Otfs.ProjectManagement.Core.Application;
using System.Web.Mvc;
using System.Linq;

namespace OpenTfsPortal.Controllers
{
    [Authorize]
    public class ProjectManagementController : ApplicationController
    {
        private IOtfsProjectServices _OtfsProjectServices;

        public ProjectManagementController(IOtfsProjectServices otfsProjectServices)
        {
            _OtfsProjectServices = otfsProjectServices;
        }

        public ActionResult Index(int projectId = 0)
        {
            var projects = _OtfsProjectServices.RetornarProjetosPorUsuario(UsuarioAutorizadoSession.Id);

            var model = new ProjectManagementViewModel
            {
                Projects = projects.ToList(),
                SelectedProjectId = projectId,
                Usuario = this.UsuarioAutorizadoSession
            };

            return View(model);
        }
    }
}

OpenTfsPortal/Views/Dashboard/DashboardAuditorFiscal.cshtml
@model OpenTfsPortal.Models.DashboardAuditorViewModel
@{
    ViewBag.Title = "Dashboard Auditor";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<aside>
    <a href="@Url.Action("Index", "ProjectManagement")" class="btn btn-link">
        <span class="glyphicon glyphicon-tasks"></span>&nbsp;LISTA DE PROJETOS
    </a>
    <hr>
    <h4>
        <small>ITERAÇÃO</small> <br>
        @Model.Interation.ToUpper()
    </h4>
    <hr>
    <h5>
        <small>Data início</small><br>
        @Model.DataInicioSprintFormatada
    </h5>
    <h5>
        <small>Data final</small><br>
        @Model.DataFimSprintFormatada
    </h5>
    <table class="table">
        <thead>
            <tr>
                <td align="center">
                    <h5 style="margin:0">
                        <small>PENDENTES</small>
                    </h5>
                </td>
                <td align="center">
                    <h5 style="margin:0">
                        <small>ANDAMENTO</small>
                    </h5>
                </td>
                <td align="center">
                    <h5 style="margin:0">
                        <small>CONCLUÍDAS</small>
                    </h5>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td align="center">
                    <h2 style="margin:0">@Model.PercentualTarefasPendentes%</h2>
                </td>
                <td align="center">
                    <h2 style="margin:0">@Model.PercentualTarefasEmaAndamento%</h2>
                </td>
                <td align="center">
                    <h2 style="margin:0">@Model.PercentualTarefasConcluidas%</h2>
                </td>
            </tr>
        </tbody>
    </table>
</aside>
<section class="dashboard-content">
    <article>
        <h4>PENDENTE <br /> <small>@Model.ItemsPendentes.Count() solicitações</small></h4>
        <hr>
        @foreach (var item in @Model.ItemsPendentes)
        {
            @Html.BacklogItemInfoPanel(item)
        }
    </article>
    <article>
        <h4>EM ANDAMENTO <br /> <small>@Model.ItemsAndamento.Count() solicitações</small></h4>
        <hr>
        @foreach (var item in @Model.ItemsAndamento)
        {
            @Html.BacklogItemInfoPanel(item)
        }
    </article>
    <article>
        <h4>PARA TESTES <br /><small>@Model.ItemsComitadas.Count() solicitações</small></h4>
        <hr>
        @foreach (var item in @Model.ItemsComitadas)
        {

            @Html.BacklogItemWarningPanel(item)

            @Html.Partial("Auditor/_tarefas_modal_aprovar", @item)
            @Html.Partial("Auditor/_tarefas_modal_reprovar", @item)
        }
    </article>
    <article>
        <h4>PARA PUBLICAÇÃO <br /><small>@Model.ItemsParaBuild.Count() solicitações</small></h4>
        <hr>
        @foreach (var item in @Model.ItemsParaBuild)
        {
            @Html.BacklogItemDeployPanel(item)

        }
    </article>
    <article>
        <h4>PUBLICADO <br /><small>@Model.ItemsPublicados.Count() solicitações</small></h4>
        <hr>
        @foreach (var item in @Model.ItemsPublicados)
        {
            @Html.BacklogItemSuccessPanel(item)
            
            @Html.Partial("Auditor/_tarefas_modal_Concluir", @item)
            @Html.Partial("Auditor/_tarefas_modal_reprovar", @item)
        }
    </article>
    @*<article>
        <h4>CONCLUIDOS <br /><small>@Model.ItemsConcluidos.Count() solicitações</small></h4>
        <hr>
        @foreach (var item in @Model.ItemsConcluidos)
        {
            @Html.BacklogItemDeployPanel(item)

        }
    </article>*@
</section>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $('a').tooltip();
    </script>
}

OpenTfsPortal/Views/Dashboard/DashboardDesenvolvedor.cshtml
@model OpenTfsPortal.Models.DashboardDesenvolvedorViewModel

@{
   ViewBag.Title = "Dashboard Desenvolvedor";
   Layout = "~/Views/Shared/_Dashboard.cshtml";

   var dicTarefas = Model.AgruparTarefasPorProjeto();
}


@section menu{
   <div>
      <a href="@Url.Action("DashboardHoras", "Produtividade")">
         <span class="glyphicon glyphicon-calendar"></span>&nbsp;
         Quadro de Horas
      </a>
   </div>
}

<section class="dashboard-content">

   @foreach (var projeto in dicTarefas)
   {
      <article>
         <h4>@projeto.Key</h4>
         <hr />
         @foreach (var task in dicTarefas[projeto.Key])
         {
            var lancamento = new OpenTfsPortal.Models.LancamentoHoraViewModel()
            {
               UserId = Model.UserId,
               TaskId = task.TaskId.Id,
               Data = DateTime.Today,
               DataLancamento = DateTime.Today,
               Title = task.Title
            };

            @Html.Partial("Desenvolvedor/_task_panel", task)
            @Html.Partial("Desenvolvedor/_hora", lancamento)
         }
      </article>
   }
</section>
@section Scripts {
   @Scripts.Render("~/bundles/jqueryval")
}

OpenTfsPortal/Views/Dashboard/DashboardInfraestrutura.cshtml
@model OpenTfsPortal.Models.DashboardInfraViewModel

@{
   ViewBag.Title = "DashboardInfraestrutura";
}

<div class="container">
   @*<div class="page-header" id="banner">
      <div class="row">
         <div class="col-lg-8 col-md-7 col-sm-6">
            <h2>SOLICITAÇÕES APROVADAS PARA PRODUÇÃO</h2>
         </div>
      </div>
   </div>*@
   <div class="row">
      <div class="col-lg-4">
         <h3>
            SISTEMA <br />
            <small>para publicação</small>
         </h3>
         <hr />
      </div>
      <div class="col-lg-8">
         <h3>
            NOTIFICAR PUBLICAÇÃO <br />
            <small>selecione ação para notificar status da publicação</small>
         </h3>
         <hr />
      </div>
      @foreach (var item in @Model.ProjetosParaCompilacao)
      {
         <div class="col-lg-4">
            <h1>
               @item.Key.Name.ToUpper()
            </h1>
            <span class="badge">@item.Value</span> solicitações para publicação
         </div>
         <div class="col-lg-6">
            <h1>
               <a href="@Url.Action("MarcarProjetoPublicado", "Dashboard", new { id = @item.Key.ProjectId.Id })" class="btn btn-lg btn-success">
                  <span class="glyphicon glyphicon-upload"></span>&nbsp;PUBLICADO
               </a>
               <a href="#" class="btn btn-lg btn-danger">
                  <span class="glyphicon glyphicon-ban-circle"></span>&nbsp;FALHA NA PUBLICAÇÃO
               </a>
            </h1>
         </div>
         <div class="col-lg-12">
            <hr />
         </div>
      }
   </div>
</div>

OpenTfsPortal/Views/Dashboard/DashboardTimer.cshtml
@model OpenTfsPortal.Models.DashboardAuditorViewModel
@{
   ViewBag.Title = "Dashboard Auditor";
   Layout = "~/Views/Shared/_Dashboard.cshtml";
}
@section menu{
   <div style="color:#fff">
      <h4>@Model.Interation</h4>
   </div>
}
<section class="dashboard-content">
   <article>
      <h4>PENDENTE <br /> <small>@Model.ItemsPendentes.Count() solicitações</small></h4>
      <hr>
      @foreach (var item in @Model.ItemsPendentes)
      {
      @Html.BacklogItemInfoPanel(item)
      }
   </article>
   <article>
      <h4>EM ANDAMENTO <br /> <small>@Model.ItemsAndamento.Count() solicitações</small></h4>
      <hr>
      @foreach (var item in @Model.ItemsAndamento)
      {
      @Html.BacklogItemInfoPanel(item)
      }
   </article>
   <article>
      <h4>PARA TESTES <br /><small>@Model.ItemsComitadas.Count() solicitações</small></h4>
      <hr>
      @foreach (var item in @Model.ItemsComitadas)
      {

      @Html.BacklogItemWarningPanel(item)

      @Html.Partial("Auditor/_tarefas_modal_aprovar", @item)
      @Html.Partial("Auditor/_tarefas_modal_reprovar", @item)
      }
   </article>
   <article>
      <h4>PARA PUBLICAÇÃO <br /><small>@Model.ItemsParaBuild.Count() solicitações</small></h4>
      <hr>
      @foreach (var item in @Model.ItemsParaBuild)
      {
      @Html.BacklogItemDeployPanel(item)

      }
   </article>
   <article>
      <h4>PUBLICADO <br /><small>@Model.ItemsPublicados.Count() solicitações</small></h4>
      <hr>
      @foreach (var item in @Model.ItemsPublicados)
      {
      @Html.BacklogItemSuccessPanel(item)

      @Html.Partial("Auditor/_tarefas_modal_Concluir", @item)
      @Html.Partial("Auditor/_tarefas_modal_reprovar", @item)
      }
   </article>
</section>
@section scripts{
   @Scripts.Render("~/bundles/jqueryval")
   <script>
      $('a').tooltip();
   </script>
}